#!/usr/bin/env node
/**
 * Post-build script to inject client bundle AND SDK into worker code
 */
const fs = require('fs');
const path = require('path');

const clientBundlePath = path.join(__dirname, '../dist/client.js');
const sdkBundlePath = path.join(__dirname, '../dist/upload-client.js');
const clientBundleModulePath = path.join(__dirname, '../src/client-bundle.ts');

try {
  // Read the built client bundle
  const clientJS = fs.readFileSync(clientBundlePath, 'utf-8');

  // Read the SDK bundle
  const sdkJS = fs.readFileSync(sdkBundlePath, 'utf-8');

  // Escape for TS string literal
  const escapedClientJS = clientJS
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');

  const escapedSDKJS = sdkJS
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');

  // Write to client-bundle.ts with both SDK and client code
  const content = `/**
 * Client bundle - auto-generated by build script
 * DO NOT EDIT MANUALLY
 *
 * Includes:
 * 1. @arke/upload-client SDK (UMD bundle)
 * 2. Client application code
 */

// SDK bundle (loaded first, creates global ArkeUploadClient)
export const sdkBundle = \`${escapedSDKJS}\`;

// Client bundle
export const clientBundle = \`${escapedClientJS}\`;
`;

  fs.writeFileSync(clientBundleModulePath, content, 'utf-8');
  console.log('✓ Client bundle and SDK injected successfully');
} catch (error) {
  console.error('✗ Failed to inject bundles:', error.message);
  process.exit(1);
}
