#!/usr/bin/env node
/**
 * Post-build script to inject client bundle into worker code
 */
const fs = require('fs');
const path = require('path');

const clientBundlePath = path.join(__dirname, '../dist/client.js');
const clientBundleModulePath = path.join(__dirname, '../src/client-bundle.ts');

try {
  // Read the built client bundle
  const clientJS = fs.readFileSync(clientBundlePath, 'utf-8');

  // Escape for TS string literal
  const escapedJS = clientJS
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');

  // Write to client-bundle.ts
  const content = `/**
 * Client bundle - auto-generated by build script
 * DO NOT EDIT MANUALLY
 */
export default \`${escapedJS}\`;
`;

  fs.writeFileSync(clientBundleModulePath, content, 'utf-8');
  console.log('✓ Client bundle injected successfully');
} catch (error) {
  console.error('✗ Failed to inject client bundle:', error.message);
  process.exit(1);
}
